### ISSUE TITLE
Diagrama de Sequência V2

### ISSUE THREAD

**Issue by EsioFreitas** [pax-app/Wiki#107]
# Descrição da Issue
Fazer a versão dois do diagrama de sequencia.

## Tasks:
- [x] Atualizar diagrama de sequência do Login
- [x] Criar diagrama de sequência do Chat
- [ ] Criar diagrama de sequência do Pós-Serviço

# Critérios de Aceitação
* Colocar artefato na Wiki
