### ISSUE TITLE
Protótipo de Alta de Fidelidade 

### ISSUE THREAD

**Issue by EsioFreitas** [pax-app/Wiki#111]
# Descrição da Issue
Fazer o protótipo de alta fidelidade seguindo o wireframe testado e manual de identidade visual.

## Tasks:
- [ ] Criar as telas seguindo os protótipos de media fidelidade 
- [ ] Adicionar a ID Visual as telas seguindo o Manual
- [ ] Adicionar o fluxo de navegação entre as telas
- [ ] Colocar na wiki telas agrupadas por feature
- [ ] Bônus: Colocar o código flutter dos elementos de maior destaque ou os nao triviais

# Critérios de Aceitação
* Colocar artefato na Wiki

**Comment by youssef-md** [comment]
O Figma que vamos fazer o protótipo de alta fidelidade esta [aqui](https://www.figma.com/file/lSRDfsDUZeiL3YiUGhEV6k/pax-prot%C3%B3tipo-alta-fidelidade?node-id=0%3A1)

E o Figma do de média fidelidade testado está [aqui](https://www.figma.com/file/cmUWUCrBPoO11hGFuuNu7z/Prot%C3%B3tipo-de-M%C3%A9dia-Fidelidade)

**Comment by EsioFreitas** [comment]
@gabrielalbino posta o que ja tem do manual aqui

**Comment by gabrielalbino** [comment]
> @gabrielalbino posta o que ja tem do manual aqui

Como disse, o manual de ID da marca não vai ajudar muito aqui, será feito uso maior do #57.
Segue abaixo o manual de id. visual para referência enquanto ele não entra na wiki

[Manual de Identidade Visual.pdf](https://github.com/pax-app/Wiki/files/3627487/Manual.de.Identidade.Visual.pdf)

**Comment by gabrielalbino** [comment]
> @gabrielalbino posta o que ja tem do manual aqui

Como disse, o manual de ID da marca não vai ajudar muito aqui, será feito uso maior do #57.
Segue abaixo o manual de id. visual para referência enquanto ele não entra na wiki

[Manual de Identidade Visual.pdf](https://github.com/pax-app/Wiki/files/3627487/Manual.de.Identidade.Visual.pdf)
