### ISSUE TITLE
Análise do questionário

### ISSUE THREAD

**Issue by lucasdutraf** [pax-app/Wiki#14]
# Descrição da Issue
Essa issue se resume a coleta de dados mais relevantes observados em cada resposta do questionário feito e a elaboração de um documento para conhecimento geral do grupo e mais embasamento teórico da ideia proposta.

## Tasks:
- [x] Fazer uma análise das palavras mais ditas, utilizando uma nuvem de palavras das questões abertas
- [ ] Verificar a validação do tema proposto através das respostas obtidas
- [x] Fazer uma verificação das principais funcionalidades requeridas pelos respondentes

## Critérios de aceitação:
- [ ] O documento deve estar presente na Wiki
- [ ] O documento elaborado deve conter os pontos chaves de todas as respostas
