### ISSUE TITLE
Script de Commits

### ISSUE THREAD

**Issue by rogerioo** [pax-app/Wiki#158]
# Descrição da Issue
Ao ver como estava sendo difícil para alguns membros se habituarem com o padrão de commit da Guia de Contribuição, resolvi fazer um script que solucionasse esse problema. Dessa forma, deixo aqui registrado esse atualização na Guia de Contribuição e o script na pasta raiz do Wiki.

## Tasks:
- [x] Colocar automaticamente a referencia da issue a partir do numero da branch
- [x] Adicionar com rapidez o Co-authored de quem está fazendo pareamento
- [x] Mensagem devidamente formatada com a mensagem do commit, referência da issue e membros pareados
- [x] Commitar todas as modificações locais com a respectiva mensagem

# Critérios de Aceitação
* Colocar artefato na Wiki
* Colocar código no repositório da Wiki
