### ISSUE TITLE
Rich Picture da visão do prestador de serviços

### ISSUE THREAD

**Issue by lucasdutraf** [pax-app/Wiki#16]
# Descrição da Issue
Conforme discutido, é necessária a elaboração de um rich picture levando em consideração o ponto de vista do prestador de serviços que usará a aplicação. Se baseando, também, na issue #1 .

## Tasks:
- [x] Fazer o Rich Picture do prestador de serviços com base nos individuais

# Critério de aceitação
 - [x] O documento deve estar na Wiki
 - [x]  O grupo deve acordar com a visão explicitada no rich picture

**Comment by youssef-md** [comment]
Criei um arquivo no Figma para padronizarmos os Rich Pictures: 
https://www.figma.com/file/3Y4xtaVPvTjbi7nUWRPah4/Desenho-2019.2?node-id=0%3A1
