### ISSUE TITLE
US53 - Contato com o prestador de serviço

### ISSUE THREAD

**Issue by lucasdutraf** [pax-app/Wiki#160]
# Descrição da Issue
Eu com usuário do sistema, desejo ter contato com o prestador de serviço para negociar os termos de serviço.

## Tasks:
- [x] Teste de echo com o https://www.websocket.org/echo.html
- [x] Tela do chat seguindo o protótipo
- [ ] Consumir o backend já implementado
- [ ] Listar mensagens como está no protótipo
- [ ] Tratar erro de problemas no envio da mensagem(problema em salvar no banco)

# Critérios de Aceitação
* Chat utilizável via interface de comunicação do usuário
* Seguir protótipo
* Consumir o Back-end implementado previamente
![image](https://user-images.githubusercontent.com/31940073/66432406-56427a00-e9f4-11e9-923a-401ec308786e.png)

**Comment by lucasdutraf** [comment]
@rogerioo @youssef-md tasks
