### ISSUE TITLE
US31 - Prestadores de serviço por categoria

### ISSUE THREAD

**Issue by lucasdutraf** [pax-app/Wiki#163]
# Descrição da Issue
Eu, como	usuário do sistema, desejo ver os prestadores de serviço por categoria de serviço	para	poder melhor encontrar uma solução para meu problema. 

A issue possui algumas lacunas de implementação, logo, é cargo da dupla deixar as telas prontas para receber tal informação do back-end posteriormente.

## Tasks:
- [x] Criar tela de listagem de prestadores por categoria
- [x] Criar tela de perfil do prestador
- [x] Adicionar navegação entre as telas
- [ ] Pegar categorias via backend
- [ ] Pegar dados do prestador via backend

# Critérios de Aceitação
* Filtragem de prestadores de serviço por categoria no back-end
* Filtragem de prestadores de serviço por categoria no front-end
* Usuário deve ser capaz de visualizar um prestador de serviço em específico ao clicar em seu nome na lista
* Usuário deve ser capaz de visualizar informações detalhadas sobre um prestador de serviço
* Fidelidade ao protótipo

![image](https://user-images.githubusercontent.com/31940073/66432902-81799900-e9f5-11e9-81b9-280f9f03e948.png)

**Comment by lucasdutraf** [comment]
@MarcosNBJ @kaiqueborges tasks!

**Comment by rogerioo** [comment]
Testar o código na branch do Front
