### ISSUE TITLE
US25 - Ordenação baseada na avaliação e preço

### ISSUE THREAD

**Issue by lucasdutraf** [pax-app/Wiki#164]
# Descrição da Issue
Eu, como	usuário do sistema	, desejo encontrar prestadores de serviço baseado primariamente na avaliação deles	para	ter maior segurança na hora de contratar um prestador de serviços

## Tasks:
- [x] Criar as entidades de review
- [x] Estruturar lógica de média de reviews para um número final
- [x] Ordenar a partir das avaliações do serviços
- [x] Ordenar a partir do preço dos serviços
- [ ] Implementar botão de opção de ordenação

# Critérios de Aceitação
* Fidelidade ao protótipo
* O usuário deve ter acesso a um botão que escolha a melhor forma de ordenação
* O usuário deve poder escolher entre ordenar por preço ou avaliação
* Back-end de avaliação implementado

![image](https://user-images.githubusercontent.com/31940073/66433496-d538b200-e9f6-11e9-91d5-6413ab2fa9c7.png)

**Comment by lucasdutraf** [comment]
@Matheusss03 @lucasdutraf Tasks

**Comment by rogerioo** [comment]
Esperando a história do Marcos

**Comment by lucasdutraf** [comment]
Fé pra isso
