### ISSUE TITLE
Enviar Pax 

### ISSUE THREAD

**Issue by lucasdutraf** [pax-app/Wiki#190]
# Descrição da Issue
O prestador de serviço deve poder enviar um Pax para o usuário o qual se estabeleceu contato.

## Tasks:
- [x] Modal para o prestador com o botão pra enviar o Pax
- [x] Tela para criar um Pax
- [x] View insets para subir o modal
- [x] Date picker
- [x] Post para criar o Pax
- [x] Integração com o Firestore para o realtime
- [x] Renderizar mensagem do pax
- [x] Renderizar popup com o pax
- [x] Conseguir identificar o ultimo pax no Firebase para mudar o UI
- [x] Atualizar para rejeitar um pax
- [x] Enviar endereço para o Pax e tratar no chat
- [x] Buscar o endereço com o address_id que o usuário enviou
- [x] Buscar o Pax para reenviar
- [x] Tratar a data que vem de um Pax existente e settar o date picker
- [x] Bloquear prestador de enviar outro Pax enquanto o usuário não realizar uma ação
- [x] Tratar caso o usuário não enviou o endereço
- [ ] Visualizar o pax em detalhes
- [x] Mensagem de confirmação da deleção do Chat

BackEnd
- [x] Rota para pegar o pax pelo chat_id
- [x] Rota para update do pax
- [x] Rota para pegar o endereço do chat
- [x] Rota para retornar um endereço
- [x] Enviar mensagem no firebase com o pax_id(para o realtime)

# Critérios de Aceitação
* Estar de acordo com o protótipo de alta fidelidade
* Aplicação de padrões de projeto
  * Adição do padrão na Wiki

![image](https://user-images.githubusercontent.com/31940073/67735564-48748900-f9e3-11e9-89b6-a19b2dc8c17e.png)

**Comment by rogerioo** [comment]
Back pronto. Mas não deu tempo para o front, ficou pra essa semana. Precisa de mais dois endpoints no back

**Comment by youssef-md** [comment]
Tasks iniciais adicinadas
