### ISSUE TITLE
Tipos de Pax no Perfil do Prestador

### ISSUE THREAD

**Issue by lucasdutraf** [pax-app/Wiki#193]
# Descrição da Issue
Para o prestador de serviços e o usuário possam visualizar seus Pax pendentes, é necessária a criação  de uma interface para tal fim. Além disso, essa issue envolve a lógica que transformará um Pax iniciado em "em progresso" tanto para o usuário quanto para o prestador de serviços.

## Tasks:

- [ ] Widget para base para os outros Pax
- [ ] Tentar gerar uma nova versão para o cancelamento do Pax(tá parecendo que apaga atualmente)
- [ ] Concluir o funcionamento para o double-check
- [ ] Conexão com o back-end para cancelar um Pax(modal pra entrar justificativa...)
- [ ] Iniciar o pax conectando o back-end

# Critérios de Aceitação
* Eu como usuário do sistema desejo acessar meus Pax pendentes
* Eu como prestador de serviço desejo iniciar um Pax
* Eu como prestador de serviço desejo finalizar um Pax

![Screenshot from 2019-11-11 21-06-40](https://user-images.githubusercontent.com/29265857/68630788-360c4c00-04c7-11ea-9b6f-02b87994f48f.png)

**Comment by youssef-md** [comment]
Tasks iniciais adicionadas

**Comment by lucasdutraf** [comment]
Acabou!!
