### ISSUE TITLE
Estabelecer conexão através da API Gateway

### ISSUE THREAD

**Issue by lucasdutraf** [pax-app/Wiki#194]
# Descrição da Issue
Como foi proposto pela equipe uma API Gateway que intermediasse todo o contato do back-end com o front-end, é necessária criação das rotas que englobem todos os serviços já implementados.

## Tasks:
   - [x] Rotas do serviço de usuários
   - [x] Rotas do serviço de review
   - [x] Rotas do serviço de category 
   - [x] Rotas do serviço de pax 

# Critérios de Aceitação
* Contemplar todo os microsserviços
