### ISSUE TITLE
Refatorações para a integração do app

### ISSUE THREAD

**Issue by youssef-md** [pax-app/Wiki#199]
# Descrição da Issue
Todas as issues menores para integrar o fluxo do app

## Tasks:
- [x] Mudar rotas para a Gateway
- [x] Dialog com Error cod. 200 ao criar uma conta, ao invés de redirecionar para a home
- [x] Atualizar sidedrawer ao final do fluxo de se tornar um prestador (@gabrielalbino doing)
- [x] Problema ao abrir a SideDrawer(após um cadastro), aparentemente por causa do isProvider estar null
- [x] Lógica do isProvider forçando ou não ao dar o push no na homepage ou no painel do prestador
- [x] Nomes dos usuários e prestadores
- [x] Renderizar as fotos dos usuários e prestadores
- [x] Fazer toda a lógica do app com base no id do usuário logado
- [x] Arrumar Perfís com o dados reais e as avaliações

**Comment by youssef-md** [comment]
Criei uma nova issue para atualizar a sidedrawer

**Comment by lucasdutraf** [comment]
Acabou!!
