### ISSUE TITLE
Ações sob um pax

### ISSUE THREAD

**Issue by youssef-md** [pax-app/Wiki#200]
# Descrição da Issue
O usuário deve ver todo o histórico de serviços que foram prestados, pendentes, confirmação da inicialização e cancelados

## Tasks:
- [x] Tela de Serviços Contratados do usuário
- [x] Card de Pax para o usuário que suporta os mais diversos status
- [ ] Buscar todos os Pax do banco de dados e do Firestore para montar um objeto que reflita o estado da aplicação

# Critérios de Aceitação

![Screenshot from 2019-11-11 21-16-29.png](https://images.zenhubusercontent.com/5b9165aaf28d730b01a456a5/cc4f1844-466d-49ef-a0f5-399a2e11b852)

**Comment by rogerioo** [comment]
#198 sendo atendida nesse issue também!

**Comment by lucasdutraf** [comment]
Acabou!!
