### ISSUE TITLE
Integrar Sentry com a API Gateway

### ISSUE THREAD

**Issue by youssef-md** [pax-app/Wiki#201]
# Descrição da Issue
Por ser um bônus muito forte e não muito complexo de ser instalado, é super válido colocarmos a ferramenta de monitoramento Sentry na API Gateway, para que nos avise de qualquer exceção que der em produção

## Tasks:
- [x] Customizar a conta do Sentry para a org
- [x] Criar projeto para a Gateway
- [x] Integrar a Gateway com o Sentry
- [x] Testar a integração forçando um erro
- [x] Retornar exceptions com um handler global
