### ISSUE TITLE
Criar Código de Contribuição

### ISSUE THREAD

**Issue by fepas** [pax-app/Wiki#21]
# Descrição da *Issue*
Realizar criação do Código de Contribuição

## Tasks:
- [ ] Criação do documento principal
- [ ] Criação de documentos auxiliares(*issue* template, *pull request* template)
- [ ] Conexão entre os documentos
# Assignees
@fepas
