### ISSUE TITLE
Análise de Sentimentos

### ISSUE THREAD

**Issue by lucasdutraf** [pax-app/Wiki#25]
# Descrição da Issue
Para que haja um controle mais aprofundado da evolução do time ao longo do semestre, será necessário coletar métricas referente aos sentimentos individuais, da progressão em relação às atividades atribuídas e da relação entre elas.
## Tasks:
- [x] Criar uma planilha semi-automática dos sentimentos individuais
- [x] Criar uma planilha semi-automática da produtividade diária individual
- [x] Criar uma planilha semi-automática da relação *Sentimentos X Produtividade*

# Assignees
@Matheusss03 
# Critérios de Aceitação
- [ ] O documento deve estar na Wiki
